(()=>{(function(){var n;let o="__ScreenShotAutomationBanner",s="__ScreenShotAutomation_DivProgress",r="__ScreenShotAutomation_DivDelay",d="__ScreenShotAutomation_SecondsLeft",l="__ScreenShotAutomation_Progress",c="__ScreenShotAutomation_Total",u="__ScreenShotAutomation_AbortBtn",m="__ScreenShotAutomation_NextBtn";function _(){let e;for(;e=document.getElementById(o);)document.body.removeChild(e);let t=`<div id='${o}'>
        <div id='${s}'><b><span rel='automation_banner_locale_string_1'>ScreenShot batch mode</span>:</b> <span rel='automation_banner_locale_string_2'>capturing Page</span> <span id='${l}'></span> <span rel='automation_banner_locale_string_6'>of</span> <span id='${c}'></span>...</div>
        <div id='${r}'><b><span rel='automation_banner_locale_string_1'>ScreenShot batch mode</span>:</b> <span rel='automation_banner_locale_string_3'>waiting the page to get rendered...</span> [<span id='${d}'></span>]</div>
        
        <div id="buttons">
            <button id='${m}' role='button'><span rel='automation_banner_locale_string_4'>Next page</span></button>
            <button id='${u}' role='button'><span rel='automation_banner_locale_string_5'>Abort task</span></button>
        </div>
        </div>`;document.body.insertAdjacentHTML("afterbegin",t);let i=document.getElementById(o);i.__screenshotIgnoredElement=1}function g(){let e=i=>{let a;return(...I)=>{a&&cancelAnimationFrame(a),a=requestAnimationFrame(()=>{i(...I)})}};var t=document.getElementById(o);document.addEventListener("scroll",e(()=>{window.scrollY>0?t.style.display="flex":t.style.display="none"}),{passive:!0}),document.getElementById(u).addEventListener("click",()=>{n&&n.postMessage({topic:"abort"})}),document.getElementById(m).addEventListener("click",()=>{n&&n.postMessage({topic:"next"})})}function p(e,t){document.getElementById(l).textContent=e,document.getElementById(c).textContent=t,document.getElementById(r).style.display="none",document.getElementById(s).style.display="initial"}function b(e){document.getElementById(s).style.display="none",document.getElementById(r).style.display="initial",document.getElementById(d).textContent=e}function y(e){document.getElementById(o).style.display=e?"flex":"none"}function f(e){for(let t in e){let i=`span[rel='${t}']`;document.querySelectorAll(i).forEach(a=>{a.textContent=e[t]})}}function v(){console.log(chrome.runtime),chrome.runtime.onConnect.addListener(e=>{e.name==="fsAutomationPort"&&(n=e,e.onMessage.addListener(t=>{switch(t.topic){case"set-progress":p(t.progress,t.total);break;case"delay-info":b(t.secsLeft);break;case"set-visible":y(t.visible);break;case"set-locale-strings":f(t.localeStrings);break}}))})}document.body&&(_(),g(),v())})();})();
//# sourceMappingURL=fsAutomationBanner.js.map

